Planning data load script
visier/api-samples pull request #40
Opened 2024-12-18 22:39 UTC by kayetan6

This PR adds a sample python script that uses the new APIs for loading data into plans.

2024-12-19 15:46 UTC, Shmalikov commented on data-intake/planning-data-load/main.py
> +    url = f"{VISIER_HOST}/{BASE_URI}/data/plans/{PLAN_ID}/scenarios/{SCENARIO_ID}?calculation={CALCULATION}&method={method}"
All sample applications in this repo is using python-sdk. 
https://github.com/visier/python-sdk

For this endpoint the package should be `visier_api_data_in`.
and the API name is `PlanningDataLoadApi`
https://github.com/visier/python-sdk/blob/main/src/visier_api_data_in/visier_api_data_in/api/planning_data_load_api.py

2024-12-19 15:53 UTC, Shmalikov requested changes

2024-12-19 15:53 UTC, Shmalikov commented on data-intake/planning-data-load/main.py
> +    url = f"{VISIER_HOST}/{BASE_URI}/data/plans/{PLAN_ID}/scenarios/{SCENARIO_ID}?calculation={CALCULATION}&method={method}"
All sample applications in this repo is using python-sdk. 
https://github.com/visier/python-sdk

For this endpoint the package should be `visier_api_data_in`.
and the API name is `PlanningDataLoadApi`
https://github.com/visier/python-sdk/blob/main/src/visier_api_data_in/visier_api_data_in/api/planning_data_load_api.py

2024-12-19 15:53 UTC, Shmalikov commented on data-intake/planning-data-load/planSchema.py
> +class PlanItem:
Visier Python-SDK is generated from openapi-specifications. One of the advantages is that all DTOs are generated automatically.
https://github.com/visier/python-sdk/blob/main/src/visier_api_data_in/visier_api_data_in/models :

plan_data_load_change_dto.py
plan_data_load_change_list_dto.py
plan_data_load_error_dto.py
plan_data_upload_response_dto.py
plan_row_data_load_response_dto.py

2025-01-29 00:42 UTC, kayetan6 commented on data-intake/planning-data-load/planSchema.py
> +class PlanItem:
Changed to use these dtos

2025-01-29 00:43 UTC, kayetan6 commented on data-intake/planning-data-load/main.py
> +    url = f"{VISIER_HOST}/{BASE_URI}/data/plans/{PLAN_ID}/scenarios/{SCENARIO_ID}?calculation={CALCULATION}&method={method}"
I wasn't aware of the python-sdks. I've updated the script to use them now.

2025-01-29 21:24 UTC, emily-watt-visier approved these changes

2025-01-31 21:30 UTC, Shmalikov requested changes

2025-01-31 21:30 UTC, Shmalikov commented on data-intake/planning-data-load/main.py
> +    missingRowErrors: List[PlanDataLoadErrorDTO] = []
Variables should be snake_case
invalid_row_messages, missing_row_errors

2025-01-31 21:30 UTC, Shmalikov commented on data-intake/planning-data-load/main.py
> +BASE_URI = "v1/planning"
These variables are not used.

2025-01-31 21:30 UTC, Shmalikov commented on data-intake/planning-data-load/main.py
> +        dataUploadRowData = data_to_upload[idx]
Variable should be in snake_case.

2025-01-31 21:30 UTC, Shmalikov commented on data-intake/planning-data-load/planSchema.py
> +from dataclasses import dataclass
To make repo, more consistent please make file name in snake_case too.

2025-01-31 21:30 UTC, Shmalikov commented on data-intake/planning-data-load/main.py
> +# Returns the response and any missing row indices.
Please rewrite  all method comments in docstring format. This helps to view comments in IDE and other tools.
def load_data_into_visier(filename, method, counter) -> DataLoadResult:
    """
    Uses the Planning Data Load API to load data into a plan.
    Returns the response and any missing row indices.
    """
    
    
![image](https://github.com/user-attachments/assets/fa0214bc-ff77-4ed4-8ca5-0ca45860d46f)

2025-01-31 23:33 UTC, Shmalikov approved these changes

2025-02-04 18:39 UTC, merged